require('profile')
require('autocmd')
require('keymap')
require('packinit')
require('lsp.mason')
require('lsp.cmp')
require('extensions.lualine')
require('extensions.autopairs')
require('extensions.bufferline')
require('extensions.treesitter')
require('extensions.gitsigns')
require('extensions.neotree')
-- require('ccls')
